# Generated by Django 4.1.5 on 2023-03-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_subsciption_food_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsciption',
            old_name='food_set',
            new_name='food',
        ),
    ]
