# Generated by Django 4.1.5 on 2023-03-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0002_food_description_food_special_price_and_more'),
        ('app_general', '0003_rename_food_set_subsciption_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsciption',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_foods.food'),
        ),
    ]
