# Generated by Django 4.1.5 on 2023-03-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0002_food_description_food_special_price_and_more'),
        ('app_general', '0004_alter_subsciption_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsciption',
            name='food',
        ),
        migrations.AddField(
            model_name='subsciption',
            name='food_set',
            field=models.ManyToManyField(to='app_foods.food'),
        ),
    ]
